# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'JXPageDemo_下拉刷新' do
  use_frameworks!


 pod 'JXPagingView/Paging', '~> 2.1'
pod 'JXSegmentedView', '~> 1.3'


post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
    end
  end
end

end

